estate/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [

    path('',views.estate,name="estate_page"),

]

info/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [

    path('',views.pinfo,name="info_page"),
    path('manu/',views.manu,name="manu_page"),

]

login/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [

    path('',views.login,name="login_page"),
    path('register/',views.register,name="register_page"),

]

square/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [

    path('',views.square,name="square_page"),

]

writing/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from login import views as login_views

from django.views import static ##新增
from django.conf import settings ##新增
from django.conf.urls import url ##新增


urlpatterns = [
    path('admin/', admin.site.urls),
    #加载login下的url
    path('login/', include(('login.urls','login'),namespace='login')),
    path('square/', include(('square.urls','square'),namespace='square')),
    path('info/', include(('info.urls','info'),namespace='info')),
    path('estate/', include(('estate.urls','estate'),namespace='estate')),
    url(r'^static/(?P<path>.*)$', static.serve,
      {'document_root': settings.STATIC_ROOT}, name='static'),
]

estate/models.py
from django.db import models

# Create your models here.

info/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

square/models.py
from django.db import models

# Create your models here.

estate/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
def estate(request):
	return render(request, 'estate/estate.html')

info/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
def manu(request):
	return render(request, 'info/manu.html')

def pinfo(request):
	return render(request, 'info/pinfo.html')

# Create your views here.

login/views.py
from django.shortcuts import render

# Create your views here.
# Create your views here.
def home(request):
	return render(request, 'login/login.html')

def register(request):
	return render(request, 'login/register.html')	

def login(request):
	return render(request, 'login/login.html')	

square/views.py
from django.shortcuts import render

# Create your views here.
def square(request):
	return render(request, 'square/square.html')

estate/templates/estate/estate.html
{% extends "login/base.html" %}

{% block head %}


    <div class="body">
        <nav class="container middle secondary">
            <a href="https://www.starbucks.com.cn/menu/" class="back">
                <img src="./svg/icon-chevron-left.svg">
                返回
            </a>

            <div class="display-1">选择</div>
            <div class="tabs-wrapper">
                <ul class="subcategories">
                    <li>
                        <a id="side_menu_all" href="{% url 'square:square_page' %}" >
                            广场
                        </a>
                    </li>
                    <li>
                        <a id="side_menu_whole_bean" href="{% url 'estate:estate_page' %}" class="active">
                            小区
                        </a>
                    </li>
                    <li>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

{% endblock %}

{% block content %}

    <header class="header">
        <button class="icon close">Close</button>
    </header>
    <div class="body">
        <div class="field search">
            <img src="./svg/icon-search.svg" class="icon">
            <input type="text" id="menu-search-input" placeholder="搜索">
        </div>
        <ul class="grid columns-4 padded-2" id="menu-search-results">
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-breakfast-blend/">
                    <div class="preview circle" style="background-image: url(/images/breakfast-blend-coffee-beans.png)"></div>
                    <strong>结果1</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-house-blend/">
                    <div class="preview circle" style="background-image: url(/images/house-blend-coffee-beans.png)"></div>
                    <strong>结果2</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-kenya/">
                    <div class="preview circle" style="background-image: url(/images/kenya-coffee-beans.png)"></div>
                    <strong>结果3</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/dark-roast/starbucks-sumatra/">
                    <div class="preview circle" style="background-image: url(/images/sumatra-coffee-beans.png)"></div>
                    <strong>结果4</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/dark-roast/starbucks-sumatra/">
                    <div class="preview circle" style="background-image: url(/images/sumatra-coffee-beans.png)"></div>
                    <strong>结果5</strong>
                </a>
            </li>
        </ul>
    </div>
    <div id="Tab" class="Tab">
        <a id="one" class="subTab text-center" href="{% url 'info:info_page' %}">
            <span class="iconfont">&#xe64d;</span>
            <div class="menu_name">个人</div>
        </a>
        <a id="two" class="subTab text-center" href="info:manu_page">
            <span class="iconfont">&#xe8ac;</span>
            <div class="menu_name">稿件</div>
        </a>
        <a id="three" class="subTab text-center" href="{% url 'square:square_page' %}">
            <span class="iconfont">&#xe64e;</span>
            <div class="menu_name">广场</div>
        </a>
        <a id="four" class="subTab text-center" href="{% url 'estate:estate_page' %}">
            <span class="iconfont">&#xe8b6;</span>
            <div class="menu_name">小区</div>
        </a>
    </div>

{% endblock %}

info/templates/info/manu.html
{% extends "login/base.html" %}

{% block head %}

    <div class="body">
        <nav class="container middle secondary">
            <div class="tabs-wrapper">
                <ul class="subcategories">
                    <li>
                        <a id="side_menu_all" href="{% url 'info:info_page' %}">
                            个人信息
                        </a>
                    </li>
                    <li>
                        <a id="side_menu_whole_bean" href="{% url 'estate:estate_page' %}" class="active">
                            我的稿件
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

{% endblock %}


{% block content %}

    <header class="header">
        <button class="icon close">Close</button>
    </header>
    <div class="body">
        <div class="field search">
            <img src="./svg/icon-search.svg" class="icon">
            <input type="text" id="menu-search-input" placeholder="搜索">
        </div>
        <ul class="grid columns-4 padded-2" id="menu-search-results">
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-breakfast-blend/">
                    <div class="preview circle" style="background-image: url(/images/breakfast-blend-coffee-beans.png)"></div>
                    <strong>结果1</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-house-blend/">
                    <div class="preview circle" style="background-image: url(/images/house-blend-coffee-beans.png)"></div>
                    <strong>结果2</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-kenya/">
                    <div class="preview circle" style="background-image: url(/images/kenya-coffee-beans.png)"></div>
                    <strong>结果3</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/dark-roast/starbucks-sumatra/">
                    <div class="preview circle" style="background-image: url(/images/sumatra-coffee-beans.png)"></div>
                    <strong>结果4</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/dark-roast/starbucks-sumatra/">
                    <div class="preview circle" style="background-image: url(/images/sumatra-coffee-beans.png)"></div>
                    <strong>结果5</strong>
                </a>
            </li>
        </ul>
    </div>

{% endblock %}

info/templates/info/pinfo.html
{% extends "login/base.html" %}

{% block head %}

<div class="body">
    <nav class="container middle secondary">
        <div class="tabs-wrapper">
            <ul class="subcategories">
                <li>
                    <a id="side_menu_all" href="{% url 'info:info_page' %}" class="active">
                        个人信息
                    </a>
                </li>
                <li>
                    <a id="side_menu_all" href="{% url 'estate:estate_page' %}">
                        我的稿件
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>

{% endblock %}

{% block content %}

    <div class="banner-info" >
            <div class="col-md-5 header-left">
                <img src="./svg/logo.svg" alt="">
            </div>
            <div class="col-md-7 header-right">
                <h6 style="padding-left: 3em;">用户签名</h6>
                <ul class="address">

                <li>
                        <ul class="address-text">
                            <li><b>用户名</b></li>
                            <li>写文</li>
                        <input type="button" onclick="make()" value="修改" style="border:0;cursor:pointer;border-radius: 15px;margin-left: 10px;">
                        </input>
                        </ul>
                    </li>
                    <li>
                        <ul class="address-text">
                            <li><b>出生日期</b></li>
                            <li>今天</li>
                        <input type="button" onclick="make()" value="修改" style="border:0;cursor:pointer;border-radius: 15px;margin-left: 10px;">
                        </input>
                        </ul>
                    </li>
                    <li>
                        <ul class="address-text">
                            <li><b>职业</b></li>
                            <li>投稿平台</li>
                        <input type="button" onclick="make()" value="修改" style="border:0;cursor:pointer;border-radius: 15px;margin-left: 10px;">
                        </input>
                        </ul>
                    </li>
                    <li>
                        <ul class="address-text">
                            <li><b>联系方式</b></li>
                            <li>暂无</li>
                        <input type="button" onclick="make()" value="修改" style="border:0;cursor:pointer;border-radius: 15px;margin-left: 10px;">
                        </input>
                        </ul>
                    </li>
                    <li>
                        <ul class="address-text">
                            <li><b>电子邮箱</b></li>
                            <li><a href=""> 电子邮箱</a></li>
                        <input type="button" onclick="make()" value="修改" style="border:0;cursor:pointer;border-radius: 15px;margin-left: 10px;">
                        </ul>
                        </input>
                    </li>

                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>

{% endblock %}

login/templates/login/base.html
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>写文</title>

	{% load static %}
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body class="lang-zh page-menu-coffee chrome non-logged-in" ontouchstart="">
	<!-- Google Tag Manager (noscript) -->
	<noscript>
		<iframe src='https://www.googletagmanager.com/ns.html?id=GTM-MGKBKT5'
		height='0' width='0' style='display:none;visibility:hidden'>
	</iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->

<div id="app-view-wrapper">
	<!-- Navigation panel -->
	<nav id="nav">
		<div class="container">
			<header class="header">
				<a class="logo" href="">
					<img src="./svg/logo.svg" alt="writing">
				</a>
				<div class="primary">
					<ul>
						<li class="stores">
							<a id="stores-primary" href="{% url 'login:login_page' %}">
								登陆
							</a>
						</li>
						<li class="account">
							<a id="account-primary" href="{% url 'login:register_page' %}">
								<span data-reactroot="" class="">注册</span>
							</a>
						</li>
						<li class="menu">
							<a id="menu-primary" href="{% url 'info:info_page' %}">
								个人信息
							</a>
						</li>

					</ul>
				</div>

				<a class="icon trigger" rel="nav-overlay" id="nav-menu" href="{% url 'square:square_page' %}">
					<img src="./svg/icon-hamburger.svg">
					<span>更多</span>
				</a>

			</header>

			{% block head %}{% endblock %}
		</div>



	</nav>


	<!-- Page content -->
<section class="join-form submit-box">
	<div class="wrapper wrapper-mobile">
		{% block content %}{% endblock %}


		</div>
	</section>


</div>

</body>
</html>

login/templates/login/login.html
{% extends "login/base.html" %}

{% block head %}

    <div class="body">
        <nav class="container middle secondary">
            <div class="tabs-wrapper">
                <ul class="subcategories">
                    <li>
                        <a id="side_menu_all" href="{% url 'login:login_page' %}" class="active">
                            登录
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

{% endblock %}

{% block content %}

    <div class="login-form">
        <div class="form-field">
            <input type="hidden" value="version">
            <div class="field floating">
                <div class="ok">
                    <input type="text" id="username" name="username" placeholder="用户名或者电子邮箱" value="" autocomplete="new-password"><label>用户名或者电子邮箱</label>
                </div>
            </div>
            <div class="password-group-field">
                <div class="field floating">
                    <div class="ok">
                        <input type="password" name="password" placeholder="密码" value="" autocomplete="new-password"><label>密码</label></div>
                    </div>
                    <div class="toggle-password hide"></div>
                </div>
        </div>
        <div class="field checkbox">
            <input type="checkbox" id="login-remember" value="on">
            <label for="login-remember"><span>下次自动登录</span></label>

        </div>
        <p><a id="sign-in-forgot-password" href="/account/forgot-password" class="link"><span>忘记密码？</span></a></p>
    </div>

    <div class="actions">
        <button class="button large" disabled="">
            <span>登录</span>
        </button>
    </div>
    
{% endblock %}

login/templates/login/register.html
{% extends "login/base.html" %}

{% block head %}

<div class="body">
    <nav class="container middle secondary">
        <div class="tabs-wrapper">
            <ul class="subcategories">
                <li>
                    <a id="side_menu_all" href="./注册.html" class="active">
                        注册
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>

{% endblock %}




{% block content %}
<div class="login-form">
    <div class="form-field">
        <input type="hidden" value="version">

        <div class="field floating">
            <div class="ok">
                <input type="text" id="username" name="username" placeholder="用户名" value="" autocomplete="new-password"><label>用户名</label>
            </div>
        </div>

        <div class="password-group-field">
            <div class="field floating">
                <div class="ok">
                    <input type="password" name="password" placeholder="密码" value="" autocomplete="new-password"><label>密码</label></div>
                </div>
                <div class="toggle-password hide"></div>
        </div>

        <div class="password-group-field">
            <div class="field floating">
                <div class="ok">
                    <input type="password" name="password" placeholder="确认密码" value="" autocomplete="new-password"><label>确认密码</label></div>
                </div>
                <div class="toggle-password hide"></div>
        </div>

        <div class="password-group-field">
            <div class="field floating">
                <div class="ok">
                    <input type="text" name="password" placeholder="手机号" value="" autocomplete="new-password" style="float: left;width: 48%;"><label>手机号</label>
                </div>
                <button class="button small" disabled="" style="float: right;">
                     <span>获取验证码</span>
                </button>
            </div>
            <div class="toggle-password hide"></div>
        </div>

        <div class="field floating">
            <div class="field floating">
                <div class="ok">
                    <input type="text" name="password" placeholder="短信验证码" value="" autocomplete="new-password"><label>短信验证码</label></div>
                </div>
                <div class="toggle-password hide"></div>
        </div>

        <div class="password-group-field">
            <div class="field floating">
                <div class="ok">
                    <input type="text" name="password" placeholder="真实姓名" value="" autocomplete="new-password"><label>真实姓名</label></div>
                </div>
                <div class="toggle-password hide"></div>
        </div>

        <div class="password-group-field">
            <div class="field floating">
                <div class="ok">
                    <input type="text" name="password" placeholder="身份证号" value="" autocomplete="new-password"><label>身份证号</label></div>
                </div>
                <div class="toggle-password hide"></div>
        </div>
        <div class="field checkbox">
                <input type="checkbox" id="login-remember" value="on">
                <label for="login-remember"><a>我已经阅读并同意条款</a></label>
        </div>
    </div>
    <div class="actions">
        <button class="button large" disabled="">
            <span>注册</span>
        </button>
    </div>
</div>

{% endblock %}

square/templates/square/square.html
{% extends "login/base.html" %}

{% block head %}

    <div class="body">
        <nav class="container middle secondary">
            <a href="" class="back">
                <img src="./svg/icon-chevron-left.svg">
                返回
            </a>

            <div class="display-1">选择</div>
            <div class="tabs-wrapper">
                <ul class="subcategories">
                    <li>
                        <a id="side_menu_all" href="{% url 'square:square_page' %}" class="active">
                            广场
                        </a>
                    </li>
                    <li>
                        <a id="side_menu_whole_bean" href="{% url 'estate:estate_page' %}">
                            小区
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

{% endblock %}

{% block content %}

    <header class="header">
        <button class="icon close">Close</button>
    </header>
    <div class="body">
        <div class="field search">
            <img src="./svg/icon-search.svg" class="icon">
            <input type="text" id="menu-search-input" placeholder="搜索">
        </div>
        <ul class="grid columns-4 padded-2" id="menu-search-results">
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-breakfast-blend/">
                    <div class="preview circle" style="background-image: url(/images/breakfast-blend-coffee-beans.png)"></div>
                    <strong>结果1</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-house-blend/">
                    <div class="preview circle" style="background-image: url(/images/house-blend-coffee-beans.png)"></div>
                    <strong>结果2</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/medium-roast/starbucks-kenya/">
                    <div class="preview circle" style="background-image: url(/images/kenya-coffee-beans.png)"></div>
                    <strong>结果3</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/dark-roast/starbucks-sumatra/">
                    <div class="preview circle" style="background-image: url(/images/sumatra-coffee-beans.png)"></div>
                    <strong>结果4</strong>
                </a>
            </li>
            <li>
                <a class="overlay-close thumbnail" href="https://www.starbucks.com.cn/menu/coffee/whole-bean/dark-roast/starbucks-sumatra/">
                    <div class="preview circle" style="background-image: url(/images/sumatra-coffee-beans.png)"></div>
                    <strong>结果5</strong>
                </a>
            </li>
        </ul>
    </div>
    <div id="Tab" class="Tab">
        <a id="one" class="subTab text-center" href="{% url 'info:info_page' %}">
            <span class="iconfont">&#xe64d;</span>
            <div class="menu_name">个人</div>
        </a>
        <a id="two" class="subTab text-center" href="info:manu_page">
            <span class="iconfont">&#xe8ac;</span>
            <div class="menu_name">稿件</div>
        </a>
        <a id="three" class="subTab text-center" href="{% url 'square:square_page' %}">
            <span class="iconfont">&#xe64e;</span>
            <div class="menu_name">广场</div>
        </a>
        <a id="four" class="subTab text-center" href="{% url 'estate:estate_page' %}">
            <span class="iconfont">&#xe8b6;</span>
            <div class="menu_name">小区</div>
        </a>
    </div>

{% endblock %}